-- Script de creacion de tablas
-- Base de Datos: Oracle Cloud

-- Vehiculos
CREATE TABLE vehiculos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patente VARCHAR2(10) NOT NULL UNIQUE,
    tipo VARCHAR2(50) NOT NULL,
    marca VARCHAR2(50),
    modelo VARCHAR2(50),
    capacidad NUMBER,
    estado VARCHAR2(20) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ubicaciones
CREATE TABLE ubicaciones (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id NUMBER NOT NULL,
    latitud NUMBER(10,6) NOT NULL,
    longitud NUMBER(10,6) NOT NULL,
    velocidad NUMBER(5,2),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ubicacion_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id)
);

-- Rutas
CREATE TABLE rutas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    origen VARCHAR2(100),
    destino VARCHAR2(100),
    distancia_km NUMBER(6,2),
    activa NUMBER(1) DEFAULT 1,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Paradas
CREATE TABLE paradas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(255),
    latitud NUMBER(10,6) NOT NULL,
    longitud NUMBER(10,6) NOT NULL,
    orden_parada NUMBER,
    ruta_id NUMBER NOT NULL,
    CONSTRAINT fk_parada_ruta FOREIGN KEY (ruta_id) REFERENCES rutas(id)
);

-- Horarios
CREATE TABLE horarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruta_id NUMBER NOT NULL,
    dia_semana VARCHAR2(20) NOT NULL,
    hora_inicio VARCHAR2(8) NOT NULL,
    hora_fin VARCHAR2(8) NOT NULL,
    frecuencia_minutos NUMBER,
    activo NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_horario_ruta FOREIGN KEY (ruta_id) REFERENCES rutas(id)
);

-- Indices
CREATE INDEX idx_vehiculo_patente ON vehiculos(patente);
CREATE INDEX idx_vehiculo_estado ON vehiculos(estado);
CREATE INDEX idx_ubicacion_vehiculo ON ubicaciones(vehiculo_id);
CREATE INDEX idx_ruta_codigo ON rutas(codigo);
CREATE INDEX idx_parada_ruta ON paradas(ruta_id);
CREATE INDEX idx_horario_ruta ON horarios(ruta_id);

-- Datos de prueba
INSERT INTO vehiculos (patente, tipo, marca, modelo, capacidad, estado) VALUES ('AABB12', 'BUS', 'Mercedes Benz', 'O500', 45, 'ACTIVO');
INSERT INTO vehiculos (patente, tipo, marca, modelo, capacidad, estado) VALUES ('CCDD34', 'BUS', 'Volvo', 'B290R', 40, 'ACTIVO');
INSERT INTO vehiculos (patente, tipo, marca, modelo, capacidad, estado) VALUES ('EEFF56', 'MICROBUS', 'Volkswagen', '9-150', 25, 'MANTENCION');

INSERT INTO rutas (codigo, nombre, descripcion, origen, destino, distancia_km, activa) VALUES ('R001', 'Centro - Estacion', 'Ruta principal al centro', 'Terminal Norte', 'Estacion Central', 8.5, 1);
INSERT INTO rutas (codigo, nombre, descripcion, origen, destino, distancia_km, activa) VALUES ('R002', 'Circunvalacion', 'Ruta circular por la ciudad', 'Plaza Principal', 'Plaza Principal', 15.0, 1);

INSERT INTO paradas (nombre, direccion, latitud, longitud, orden_parada, ruta_id) VALUES ('Terminal Norte', 'Av. Norte 100', -33.4100, -70.6500, 1, 1);
INSERT INTO paradas (nombre, direccion, latitud, longitud, orden_parada, ruta_id) VALUES ('Plaza Central', 'Calle Principal 500', -33.4372, -70.6506, 2, 1);
INSERT INTO paradas (nombre, direccion, latitud, longitud, orden_parada, ruta_id) VALUES ('Estacion Central', 'Av. Estacion 1', -33.4520, -70.6800, 3, 1);

INSERT INTO horarios (ruta_id, dia_semana, hora_inicio, hora_fin, frecuencia_minutos, activo) VALUES (1, 'MONDAY', '06:00', '22:00', 15, 1);
INSERT INTO horarios (ruta_id, dia_semana, hora_inicio, hora_fin, frecuencia_minutos, activo) VALUES (1, 'TUESDAY', '06:00', '22:00', 15, 1);
INSERT INTO horarios (ruta_id, dia_semana, hora_inicio, hora_fin, frecuencia_minutos, activo) VALUES (1, 'SATURDAY', '07:00', '20:00', 20, 1);

COMMIT;
